import localFont from "next/font/local";
import "./globals.css";

const geistMono = localFont({
  src: "./fonts/CenturyGothic.ttf",
  variable: "--font-geist-century",
  weight: "100 900",
});

export const metadata = {
  title: "HK Productions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistMono.variable} antialiased font-century bg-zinc-900 text-white`}
      >
        {children}
      </body>
    </html>
  );
}
